export const DepartmentNames = [
  "Administration",
  "Business Development",
  "Business Intelligence (BI)",
  "Cloud Computing",
  "Communications",
  "Compliance",
  "Corporate Social Responsibility (CSR)",
  "Customer Service",
  "Cybersecurity",
  "Data Analytics",
  "Database Administration",
  "DevOps",
  "Enterprise Architecture",
  "Environmental Health and Safety (EHS)",
  "Event Management",
  "Facilities Management",
  "Finance",
  "Human Resources (HR)",
  "IT Infrastructure",
  "IT Project Management",
  "IT Support/Help Desk",
  "Innovation",
  "Internal Audit",
  "Investor Relations",
  "Legal",
  "Logistics",
  "Marketing",
  "Operations",
  "Procurement/Purchasing",
  "Product Management",
  "Public Relations (PR)",
  "Quality Assurance (QA)",
  "Research and Development (R&D)",
  "Risk Management",
  "Sales",
  "Software Development",
  "Strategy and Planning",
  "Supply Chain Management",
  "Training and Development",
];
