const toolbarButtons = [
  "camera",
  "chat",
  "closedcaptions",
  "desktop",
  "download",
  "filmstrip",
  "fullscreen",
  "hangup",
  "help",
  "highlight",
  "linktosalesforce",
  "livestreaming",
  "microphone",
  "noisesuppression",
  "participants-pane",
  "profile",
  "raisehand",
  "select-background",
  "settings",
  "shareaudio",
  "sharedvideo",
  "shortcuts",
  "stats",
  "tileview",
  "toggle-camera",
  "whiteboard",
];

export const JitsiConfigOverwrite = {
  disableAddingBackgroundImages: true,
  startWithAudioMuted: true,
  defaultRemoteDisplayName: "User",
  disableModeratorIndicator: true,
  readOnlyName: true,
  hiddenPremeetingButtons: ["invite", "select-background", "settings"],
  toolbarButtons,
  lobby: {
    enabled: false,
  },
};
